### ISSUE TITLE
README incorrect

### ISSUE THREAD

**Issue by joesanford** [FinNLP/en-inflectors#1]
On the line stating`instanceB.toPlural(); // ellipses (no change)` this actually is a change (ellipsis vs. ellipses).

**Comment by alexcorvi** [comment]
Here's where the instance is created (copied from readme.md)

```javascript
const instanceB = new Inflectors("ellipses"); // <--- "ellipses"
```

When you call the method `instanceB.toSingular()` the method will merely return the the singular form of `ellipses` which is `ellipsis`, It won't mutate the any of the class properties.

So I'm referring to "ellipses" (the input that the instance was instantiated with) when I say "no change".

**Comment by joesanford** [comment]
I misread, apologies.
